[package]
name = "strategically-pedalling"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2018"

[dependencies]
euphony = "0.1"
synths = { path = "../../synths" }

[build-dependencies]
euphony-build = "0.1"
