[samples]
bd = "clean://tidalcycles/sounds-dirty/bd"
sd = "clean://tidalcycles/sounds-dirty/sn"
hh = "clean://tidalcycles/sounds-tr808-fischer/ch8"
cy = "clean://tidalcycles/sounds-tr808-fischer/cy8"
ht = "clean://tidalcycles/sounds-tr808-fischer/ht8"
lt = "clean://tidalcycles/sounds-tr808-fischer/lt8"
mt = "clean://tidalcycles/sounds-tr808-fischer/mt8"
